### ISSUE TITLE
Make a new release for AppCenter

### ISSUE THREAD

**Issue by JeysonFlores** [JeysonFlores/switcher#22]
Make a new release for AppCenter that features the solution for the issue #20 in the PR #21

**Tasks:**
- [ ] Modify the meson.build file 
- [ ] Modify the README.md file
- [ ] Modify the appdata.xml file
- [ ] Create the release
- [ ] Make the PR to [elementary/appcenter-reviews](https://github.com/elementary/appcenter-reviews)
